version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/house-registry" 
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"
