name: Spring Projects CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: 'maven'

      - name: Build and test
        working-directory: ./house-registry
        run: ./mvnw -B clean package

      - name: Build Docker image
        working-directory: ./house-registry
        shell: bash
        run: docker build -t house-registry:latest .

      - name: Build and test
        working-directory: ./authorization-with-keycloak
        run: ./mvnw -B clean package

      - name: Build Docker image
        working-directory: ./authorization-with-keycloak
        shell: bash
        run: docker build -t authorization-with-keycloak:latest .
